[project]
name = "pt1diagnosis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
# ADD THE LIBRARIES HERE:
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "pandas",
    "scikit-learn",
    "scikit-image",
    "matplotlib",
    "seaborn",
    "pillow",
    "torch-geometric",
    "openpyxl>=3.1.5",
    "pyrefly>=0.45.0",
    "torch-cluster",
    "torch-scatter",
    "torch-sparse",
    "torch-spline-conv",
    "mlflow>=3.12.0",
    "torchinfo>=1.8.0",
    "scipy-stubs~=1.17.1",
    "psutil>=7.2.2",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = false

[tool.uv.sources]
torch-cluster = { url = "https://data.pyg.org/whl/torch-2.5.0%2Bcu121/torch_cluster-1.6.3%2Bpt25cu121-cp312-cp312-linux_x86_64.whl" }
torch-scatter = { url = "https://data.pyg.org/whl/torch-2.5.0%2Bcu121/torch_scatter-2.1.2%2Bpt25cu121-cp312-cp312-linux_x86_64.whl" }
torch-sparse = { url = "https://data.pyg.org/whl/torch-2.5.0%2Bcu121/torch_sparse-0.6.18%2Bpt25cu121-cp312-cp312-linux_x86_64.whl" }
torch-spline-conv = { url = "https://data.pyg.org/whl/torch-2.5.0%2Bcu121/torch_spline_conv-1.2.2%2Bpt25cu121-cp312-cp312-linux_x86_64.whl" }

[dependency-groups]
dev = [
    "commitizen>=4.13.9",
    "pandas-stubs~=2.3.3",
    "scipy-stubs>=1.17.1.5",
]
